module.exports = [
    {above38: true, hasRisk: false, ageInHours: 24, bilirubin: 10.5, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 1}},
    {above38: true, hasRisk: false, ageInHours: 48, bilirubin: 15.5, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 1}},
    {above38: true, hasRisk: false, ageInHours: 96, bilirubin: 19.8, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 1}},
    {above38: true, hasRisk: false, ageInHours: 180, bilirubin: 21.8, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 1}},
    {above38: true, hasRisk: false, ageInHours: 48, bilirubin: 20, expectedResult: { needLightTreatment: true, transfusionResult: 'התראה', riskZone: 1}},
    {above38: true, hasRisk: false, ageInHours: 48, bilirubin: 22, expectedResult: { needLightTreatment: true, transfusionResult: 'עובר', riskZone: 1}},
    {above38: true, hasRisk: true, ageInHours: 24, bilirubin: 9, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 1}},
    {above38: true, hasRisk: true, ageInHours: 48, bilirubin: 13.6, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 1}},
    {above38: true, hasRisk: true, ageInHours: 96, bilirubin: 18, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 1}},
    {above38: true, hasRisk: true, ageInHours: 180, bilirubin: 18.5, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 1}},
    {above38: true, hasRisk: true, ageInHours: 48, bilirubin: 16.6, expectedResult: { needLightTreatment: true, transfusionResult: 'התראה IVIG', riskZone: 1}},
    {above38: true, hasRisk: true, ageInHours: 48, bilirubin: 18.5, expectedResult: { needLightTreatment: true, transfusionResult: 'עובר', riskZone: 1}},
    {above38: false, hasRisk: false, ageInHours: 24, bilirubin: 8.8, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 1}},
    {above38: false, hasRisk: false, ageInHours: 48, bilirubin: 13.6, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 1}},
    {above38: false, hasRisk: false, ageInHours: 96, bilirubin: 18, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 1}},
    {above38: false, hasRisk: false, ageInHours: 180, bilirubin: 18.5, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 1}},
    {above38: false, hasRisk: false, ageInHours: 48, bilirubin: 16.6, expectedResult: { needLightTreatment: true, transfusionResult: 'התראה', riskZone: 1}},
    {above38: false, hasRisk: false, ageInHours: 48, bilirubin: 18.6, expectedResult: { needLightTreatment: true, transfusionResult: 'עובר', riskZone: 1}},
    {above38: false, hasRisk: true, ageInHours: 24, bilirubin: 7.5, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 1}},
    {above38: false, hasRisk: true, ageInHours: 48, bilirubin: 11, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 2}},
    {above38: false, hasRisk: true, ageInHours: 96, bilirubin: 18, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 3}},
    {above38: false, hasRisk: true, ageInHours: 180, bilirubin: 16, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 2}},
    {above38: false, hasRisk: true, ageInHours: 48, bilirubin: 14.8, expectedResult: { needLightTreatment: true, transfusionResult: 'התראה IVIG', riskZone: 1}},
    {above38: false, hasRisk: true, ageInHours: 48, bilirubin: 16.6, expectedResult: { needLightTreatment: true, transfusionResult: 'עובר', riskZone: 1}},
    {above38: true, hasRisk: false, ageInHours: 24, bilirubin: 10, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 1}},
    {above38: true, hasRisk: false, ageInHours: 48, bilirubin: 14, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 1}},
    {above38: true, hasRisk: false, ageInHours: 96, bilirubin: 18.5, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 1}},
    {above38: true, hasRisk: false, ageInHours: 180, bilirubin: 20, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 1}},
    {above38: true, hasRisk: true, ageInHours: 24, bilirubin: 8, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 1}},
    {above38: false, hasRisk: false, ageInHours: 24, bilirubin: 8, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 1}},
    {above38: true, hasRisk: true, ageInHours: 48, bilirubin: 12.8, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 2}},
    {above38: true, hasRisk: true, ageInHours: 96, bilirubin: 17, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 2}},
    {above38: false, hasRisk: true, ageInHours: 24, bilirubin: 7.7, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 2}},
    {above38: false, hasRisk: true, ageInHours: 48, bilirubin: 11.2, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 2}},
    {above38: false, hasRisk: true, ageInHours: 96, bilirubin: 15.6, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 2}},
    {above38: false, hasRisk: true, ageInHours: 180, bilirubin: 16, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 2}},
    {above38: true, hasRisk: true, ageInHours: 24, bilirubin: 7.6, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 2}},
    {above38: true, hasRisk: true, ageInHours: 48, bilirubin: 12, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 2}},
    {above38: true, hasRisk: true, ageInHours: 96, bilirubin: 16, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 2}},
    {above38: true, hasRisk: true, ageInHours: 180, bilirubin: 16, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 2}},
    {above38: false, hasRisk: true, ageInHours: 24, bilirubin: 6.5, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 2}},
    {above38: true, hasRisk: false, ageInHours: 24, bilirubin: 7.7, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 2}},
    {above38: true, hasRisk: false, ageInHours: 48, bilirubin: 12.9, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 2}},
    {above38: true, hasRisk: false, ageInHours: 96, bilirubin: 17.2, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 2}},
    {above38: true, hasRisk: false, ageInHours: 180, bilirubin: 17, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 2}},
    {above38: false, hasRisk: false, ageInHours: 24, bilirubin: 7.8, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 2}},
    {above38: false, hasRisk: false, ageInHours: 96, bilirubin: 17.2, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 0}},
    {above38: false, hasRisk: false, ageInHours: 180, bilirubin: 17.2, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 2}},
    {above38: true, hasRisk: true, ageInHours: 24, bilirubin: 5.3, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: true, hasRisk: true, ageInHours: 48, bilirubin: 9.3, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: true, hasRisk: true, ageInHours: 96, bilirubin: 13, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: true, hasRisk: true, ageInHours: 180, bilirubin: 14, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: false, hasRisk: true, ageInHours: 24, bilirubin: 5.3, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: false, hasRisk: true, ageInHours: 48, bilirubin: 9.3, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: false, hasRisk: true, ageInHours: 96, bilirubin: 13, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: false, hasRisk: true, ageInHours: 180, bilirubin: 14, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: true, hasRisk: false, ageInHours: 24, bilirubin: 5.3, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: true, hasRisk: false, ageInHours: 48, bilirubin: 9.3, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: true, hasRisk: false, ageInHours: 96, bilirubin: 13, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: true, hasRisk: false, ageInHours: 180, bilirubin: 14, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: false, hasRisk: false, ageInHours: 24, bilirubin: 5.3, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: false, hasRisk: false, ageInHours: 48, bilirubin: 9.3, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: false, hasRisk: false, ageInHours: 96, bilirubin: 13, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: false, hasRisk: false, ageInHours: 180, bilirubin: 14, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 3}},
    {above38: true, hasRisk: false, ageInHours: 24, bilirubin: 4.7, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: true, hasRisk: false, ageInHours: 48, bilirubin: 8.2, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: true, hasRisk: false, ageInHours: 96, bilirubin: 12, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: true, hasRisk: false, ageInHours: 180, bilirubin: 12, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: true, hasRisk: true, ageInHours: 24, bilirubin: 4.7, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: true, hasRisk: true, ageInHours: 48, bilirubin: 8.2, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: true, hasRisk: true, ageInHours: 96, bilirubin: 12, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: true, hasRisk: true, ageInHours: 180, bilirubin: 12, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: false, hasRisk: false, ageInHours: 24, bilirubin: 4.7, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: false, hasRisk: false, ageInHours: 48, bilirubin: 8.2, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: false, hasRisk: false, ageInHours: 96, bilirubin: 12, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: false, hasRisk: false, ageInHours: 180, bilirubin: 12.6, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: false, hasRisk: true, ageInHours: 24, bilirubin: 4.7, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: false, hasRisk: true, ageInHours: 48, bilirubin: 8.2, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: false, hasRisk: true, ageInHours: 96, bilirubin: 12, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: false, hasRisk: true, ageInHours: 180, bilirubin: 12, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 4}},
    {above38: true, hasRisk: false, ageInHours: 4, bilirubin: 2.1, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 0}},
    {above38: true, hasRisk: true, ageInHours: 4, bilirubin: 2.1, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 0}},
    {above38: false, hasRisk: false, ageInHours: 4, bilirubin: 2.1, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 0}},
    {above38: false, hasRisk: true, ageInHours: 4, bilirubin: 2.1, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 0}},
    {above38: true, hasRisk: false, ageInHours: 4, bilirubin: 1.9, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 0}},
    {above38: true, hasRisk: true, ageInHours: 4, bilirubin: 1.9, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 0}},
    {above38: false, hasRisk: false, ageInHours: 4, bilirubin: 1.9, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 0}},
    {above38: false, hasRisk: true, ageInHours: 4, bilirubin: 1.9, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 0}},
    {above38: true, hasRisk: false, ageInHours: 4, bilirubin: 4.1, expectedResult: { needLightTreatment: true, transfusionResult: 'עובר גדול מגיל ילוד', riskZone: 0}},
    {above38: true, hasRisk: true, ageInHours: 4, bilirubin: 4.1, expectedResult: { needLightTreatment: true, transfusionResult: 'עובר גדול מגיל ילוד', riskZone: 0}},
    {above38: false, hasRisk: false, ageInHours: 4, bilirubin: 4.1, expectedResult: { needLightTreatment: true, transfusionResult: 'עובר גדול מגיל ילוד', riskZone: 0}},
    {above38: false, hasRisk: true, ageInHours: 4, bilirubin: 4.1, expectedResult: { needLightTreatment: true, transfusionResult: 'עובר גדול מגיל ילוד', riskZone: 0}},
    {above38: true, hasRisk: false, ageInHours: 12, bilirubin: 8, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 1}},
    {above38: true, hasRisk: true, ageInHours: 12, bilirubin: 6.5, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 2}},
    {above38: false, hasRisk: false, ageInHours: 12, bilirubin: 6.2, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 0}},
    {above38: false, hasRisk: true, ageInHours: 12, bilirubin: 5.5, expectedResult: { needLightTreatment: true, transfusionResult: 'ריק', riskZone: 2}},
    {above38: true, hasRisk: false, ageInHours: 12, bilirubin: 7.5, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 1}},
    {above38: true, hasRisk: true, ageInHours: 12, bilirubin: 6.3, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 2}},
    {above38: false, hasRisk: false, ageInHours: 12, bilirubin: 6, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 2}},
    {above38: false, hasRisk: true, ageInHours: 12, bilirubin: 5, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 2}},
    {above38: true, hasRisk: false, ageInHours: 9, bilirubin: 6.8, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 0}},
    {above38: true, hasRisk: true, ageInHours: 9, bilirubin: 5, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 0}},
    {above38: false, hasRisk: false, ageInHours: 9, bilirubin: 5, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 0}},
    {above38: false, hasRisk: true, ageInHours: 9, bilirubin: 3.9, expectedResult: { needLightTreatment: false, transfusionResult: 'ריק', riskZone: 0}},
]

// ADD IT ONCE CONTRACDICTION FIXED {above38: false, hasRisk: false, ageInHours: 48, bilirubin: 12.9, expectedResult: { needLightTreatment: false, riskZone: 2}}, 

// Tal- there's a confilict with this sample- there's another sample (line 96) with different expected result
// ADD IT AFTER WE AGREED ON REMOVAL OF RELEASE TEXT{above38: false, hasRisk: false, ageInHours: 12, bilirubin: 6.2, expectedResult: { needLightTreatment: true, riskZone: 2}},

//ADD THESE after checking with Shlomo that we need to change the graphs accordingly...
// {above38: true, hasRisk: false, ageInHours: 9, bilirubin: 7.2, expectedResult: { needLightTreatment: true, riskZone: 0}},
// {above38: true, hasRisk: true, ageInHours: 9, bilirubin: 5.5, expectedResult: { needLightTreatment: true, riskZone: 0}},
// {above38: false, hasRisk: false, ageInHours: 9, bilirubin: 5.5, expectedResult: { needLightTreatment: true, riskZone: 0}},
// {above38: false, hasRisk: true, ageInHours: 9, bilirubin: 4.2, expectedResult: { needLightTreatment: true, riskZone: 0}},